[package]
edition = "2021"
name = "ppaass-agent-windows"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ppaass_agent_windows_lib"
path = "src/lib.rs"

[[bin]]
name = "ppaass-agent"
path = "src/bin/bin.rs"

[dependencies]
ppaass-protocol={git = "https://github.com/quhxuxm/ppaass-protocol.git", branch = "main"}
ppaass-io={git = "https://github.com/quhxuxm/ppaass-io.git", branch = "main"}
ppaass-crypto={git = "https://github.com/quhxuxm/ppaass-crypto.git", branch = "main"}
anyhow = "1.0"
async-trait = "0.1"
bytecodec = "0.4"
bytes = "1.5"
futures = "0.3"
futures-util = {version = "0.3", features = ["std"]}
httpcodec = {version = "0.2"}
lazy_static = {version = "1.4"}
pin-project = {version = "1.1"}
pretty-hex = {version = "0.3"}
serde = {version = "1.0"}
serde_derive = {version = "1.0"}
tokio = {version = "1.34", features = ["macros", "time", "net", "io-util", "rt-multi-thread", "fs"]}
tokio-util = {version = "0.7", features = ["codec"]}
toml = {version = "0.8"}
url = {version = "2.4"}
thiserror = {version = "1.0"}
tokio-stream = {version = "0.1"}
chrono = {version = "0.4"}
derive_more= {version = "0.99"}
log4rs = {version = "1.2"}
log = {version = "0.4"}
